
INPUT_FILE_DIRECTORIES=$PWD/data
TASKLIB=$PWD/src/
COMMAND_LINE="python /usr/local/bin/hisat_wrapper.py -f -x $INPUT_FILE_DIRECTORIES/index/22_20-21M_snp -U $INPUT_FILE_DIRECTORIES/reads/reads_1.fa -S eg1.sam"



CONTAINER_OVERRIDE_MEMORY=3100
JOB_DEFINITION_NAME="Hisat2"
JOB_ID=HISAT_ALGN__$1
JOB_QUEUE=TedTest
S3_ROOT=s3://moduleiotest
WORKING_DIR=$PWD/job_52345

DOCKER_CONTAINER=genepattern/docker-hisat2


