
INPUT_FILE_DIRECTORIES=$PWD/data
TASKLIB=$PWD/src/
COMMAND_LINE="hisat2 -f -x $INPUT_FILE_DIRECTORIES/index/22_20-21M_snp -1 $INPUT_FILE_DIRECTORIES/reads/reads_1.fa -2 $INPUT_FILE_DIRECTORIES/reads/reads_2.fa -S eg2.sam"



CONTAINER_OVERRIDE_MEMORY=3100
JOB_DEFINITION_NAME="Hisat2"
JOB_ID=HISAT_PAIRED_$1
JOB_QUEUE=TedTest
S3_ROOT=s3://moduleiotest
WORKING_DIR=$PWD/job_52345

DOCKER_CONTAINER=genepattern/docker-hisat2


