
INPUT_FILE_DIRECTORIES=$PWD/data
TASKLIB=$PWD/src/
COMMAND_LINE="hisat2-build $INPUT_FILE_DIRECTORIES/reference/22_20-21M.fa --snp $INPUT_FILE_DIRECTORIES/reference/22_20-21M.snp 22_20-21M_snp"

CONTAINER_OVERRIDE_MEMORY=3100
JOB_DEFINITION_NAME="Hisat2"
JOB_ID=HISAT2_IDX__$1
JOB_QUEUE=TedTest
S3_ROOT=s3://moduleiotest
WORKING_DIR=$PWD/job_52345

DOCKER_CONTAINER=genepattern/docker-hisat2


